### ISSUE TITLE
How to optimize the DB queries?

### ISSUE THREAD

**Issue by timothepearce** [timothepearce/laravel-time-series#19]
### Discussed in https://github.com/timothepearce/laravel-quasar/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **timothepearce** December 30, 2021</sup>
Regarding the architecture of the `quasar_projections` table, it seems possible to create some kind of composite index to optimize the speed.</div>

**Comment by tim-tepia** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @jswanson4917, @GabrielWongAu, @hannoeru, @Hunsmore, @Zizwar, @daetalys, @richardzhu, @mac-code, @akkie, @vingel, @cryptowen, @thekasailife, @danbruder, @moonpalace806, @mazkarow, @sheplu, @369gtech, @SinuxLee, @arcangelw, @shirishkz, @bryantbeckford, @TRUBDUBZ, @kung8kungkung, @guidefreitas, @olucaslrc, @takaradariku, @clayrat, @CharesFang, @simon-lentz, @yenwel, @renning22, @matiasinsaurralde, @KernelCode, @strogiyotec, @karimra, @courthub74, @Byron, @fafifox, @cotemper, @aelohin, @lispc, @bnclt, @Polobandit23, @Yohuan, @tablee425, @Abhijnan-Bajpai, @Jaex, @en0c-026, @mehranj73, @samfatoks

**Comment by metadetron** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @nhannguyen95, @mmervecerit, @joaocunha, @alfah13, @tecnomnyk, @YTVRCI, @gretard
