### ISSUE TITLE
Getting Projectable error

### ISSUE THREAD

**Issue by hiteshsamcom** [timothepearce/laravel-time-series#22]
![image](https://user-images.githubusercontent.com/92365321/157388930-80fd94cf-db1c-42e7-be03-10d853ade351.png)

Getting this error into PHP 7.4 and Laravel 8 when I define this in my model 

```
use TimothePearce\TimeSeries\Projectable;

use Projectable;
```

**Comment by hiteshsamcom** [comment]
@timothepearce any update?

**Comment by timothepearce** [comment]
Hi @hiteshsamcom I'll look at it tonight ;)

**Comment by hiteshsamcom** [comment]
I think I'm using PHP 7.4 that's why it's giving the error, It must be run into PHP 8.0+

**Comment by timothepearce** [comment]
Ok so you must use another namespace regarding the `Projectable` trait:

```php
use TimothePearce\TimeSeries\Models\Traits\Projectable;
```

Also, the package isn't compatible with PHP 7.4, you must upgrade to 8.0.
